Adjust faq mobile view [28]
ShenaniganDApp/ShenaniganDApp.github.io pull request #33
Opened 2020-09-19 11:45 UTC by bighappytrees

2020-09-19 19:54 UTC, youngkidwarrior requested changes

2020-09-19 19:54 UTC, youngkidwarrior commented on src/Sections/QuestionSection.js
> +	padding: none;
Let's keep the padding on the top and bottom. 

`padding: 1rem 0;`

2020-09-19 19:54 UTC, youngkidwarrior commented on src/Sections/QuestionSection.js
> +	border-radius: 0 0 25px 25px;
This will change it on the widescreen version on desktop. This goes in the media query.

2020-09-19 19:56 UTC, bighappytrees commented on src/Sections/QuestionSection.js
> +	border-radius: 0 0 25px 25px;
gah

2020-09-20 21:30 UTC, youngkidwarrior approved these changes

2020-09-21 03:19 UTC, merged